/**
 * Every GLB the app loads (pure data — no three.js imports, so the 2D site can use it). Files are produced by `npm run assets` (scripts/build-assets.mjs)
 * from the CC0 sources in assets-src/. Props have a bottom-center pivot and face +Z.
 */
export const FURNITURE = [
  'books', 'bookcaseClosedWide', 'cabinetTelevision', 'chairCushion', 'chairDesk', 'coatRackStanding', 'computerKeyboard',
  'computerScreen', 'lampSquareFloor', 'laptop', 'plantSmall1', 'pottedPlant', 'rugRectangle', 'rugRound',
  'sideTable', 'speaker', 'table', 'televisionModern',
] as const
export const NATURE = ['flower_redA', 'flower_yellowA'] as const
/** Realistic CC0 furniture from Poly Haven — real-world meters (scale 1), bottom-center pivot. */
export const POLYHAVEN = [
  'SchoolDesk_01', 'SchoolChair_01', 'metal_office_desk', 'sofa_02', 'modern_arm_chair_01',
  'modern_coffee_table_01', 'wooden_display_shelves_01',
] as const
/** Procedural trees + bush generated by EZ-Tree in the pipeline (scripts/build-trees.mjs), real size. */
export const TREES = ['oak', 'ash', 'aspen', 'pine', 'bush'] as const
export const CHARACTERS = [
  'male-a', 'male-b', 'male-c', 'male-d', 'male-e', 'male-f',
  'female-a', 'female-b', 'female-c', 'female-d', 'female-e', 'female-f',
] as const

export type FurnitureName = (typeof FURNITURE)[number]
export type NatureName = (typeof NATURE)[number]
export type PolyhavenName = (typeof POLYHAVEN)[number]
export type TreeName = (typeof TREES)[number]
export type PropName = FurnitureName | NatureName | PolyhavenName | TreeName
export type CharacterVariant = (typeof CHARACTERS)[number]

/** Kenney furniture is ~half real size; ×2 makes a desk ≈ 0.77 m tall. */
export const FURNITURE_SCALE = 2
/** Kenney nature-kit props (flowers). */
export const NATURE_SCALE = 3.5
/** Mini characters are 0.67 units tall; ×2.5 ≈ 1.7 m, matching the player capsule. */
export const CHARACTER_SCALE = 2.5

const isNature = (name: PropName): name is NatureName => (NATURE as readonly string[]).includes(name)
const isPolyhaven = (name: PropName): name is PolyhavenName => (POLYHAVEN as readonly string[]).includes(name)

const isTree = (name: PropName): name is TreeName => (TREES as readonly string[]).includes(name)

const propFolder = (name: PropName) =>
  isNature(name) ? 'nature' : isPolyhaven(name) ? 'polyhaven' : isTree(name) ? 'trees' : 'furniture'
export const propUrl = (name: PropName) => `/models/${propFolder(name)}/${name}.glb`
export const propScale = (name: PropName) => (isNature(name) ? NATURE_SCALE : isPolyhaven(name) || isTree(name) ? 1 : FURNITURE_SCALE)
export const characterUrl = (variant: CharacterVariant) => `/models/characters/${variant}.glb`
export const ANIMATIONS_URL = '/models/characters/animations.glb'
